name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    uses: oapi-codegen/actions/.github/workflows/ci.yml@a4ae25b391bf6689acc6983e1e801237d8d515fc # v0.3.0
    with:
      excluding_versions: '["1.20", "1.21"]'
