name: Ensure generated files are up-to-date
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # perform matrix testing to give us an earlier insight into issues with different versions of supported major versions of Go
      matrix:
        version:
        # versions of Go that this module can still be built with (and therefore are "supported" by this project)
        - "1.22"
        # actively supported versions of Go
        - "1.23"
        - "1.24"
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ matrix.version }}

      - name: Run `make generate`
        run: make generate

      - name: Check for no untracked files
        run: git status && git diff-index --quiet HEAD --
